name: Build and Push Container

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Notebook Container
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build and push image with repo2docker
        uses: jupyterhub/repo2docker-action@master
        with:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/my_research_project
